# Generated by Django 4.1 on 2022-12-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rasm',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
